{% set version = "1.6.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: 0cb251453147421c0c807587123e733b32346b9756c8594018c637ec374a63f4

build:
  number: 0

requirements:
  build:
    - rust
    - binutils              # [linux]
    - {{native}}binutils    # [win]

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  summary: A command-line benchmarking tool
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
