{% set version = "1.9.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: c2b1c6b6364b849acad43dc740c693f5b75a1a4649f24f43967a98c59ad9e9f7

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}   # [unix]
    - {{native}}binutils    # [win]

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
